export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAN_AUTH_STATE = "CLEAN_AUTH_STATE";

export const GET_FARMS_LOADING = "GET_FARMS_LOADING";
export const GET_FARMS_SUCCESS = "GET_FARMS_SUCCESS";
export const GET_FARMS_FAIL = "GET_FARMS_FAIL";

export const CREATE_FARMS_LOADING = "CREATE_FARMS_LOADING";
export const CREATE_FARMS_SUCCESS = "CREATE_FARMS_SUCCESS";
export const CREATE_FARMS_FAIL = "CREATE_FARMS_FAIL";

export const GET_DEVICE_LOADING = "GET_DEVICE_LOADING";
export const GET_DEVICE_SUCCESS = "GET_DEVICE_SUCCESS";
export const GET_DEVICE_FAIL = "GET_DEVICE_FAIL";

export const GET_CONTROL_LOADING = "GET_CONTROL_LOADING";
export const GET_CONTROL_SUCCESS = "GET_CONTROL_SUCCESS";
export const GET_CONTROL_FAIL = "GET_CONTROL_FAIL";
